<a href="https://colab.research.google.com/github/hamzehdehghan/DeepLearnign_1/blob/main/Churn_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [7]:
data = pd.read_csv('Churn_Modelling.csv')
x = data.iloc[:,3:-1].values
y = data.iloc[:,-1].values
x[0:10, :]

array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [645, 'Spain', 'Male', 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [822, 'France', 'Male', 50, 7, 0.0, 2, 1, 1, 10062.8],
       [376, 'Germany', 'Female', 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [501, 'France', 'Male', 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [684, 'France', 'Male', 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
label =LabelEncoder()
x[:,2]=label.fit_transform(x[:,2])
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
x[:, 7] = label.fit_transform(x[:, 7])
x.shape


In [9]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
scaler = StandardScaler()
x = scaler.fit_transform(x)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [ ]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(units = 6 , activation = 'relu'))
model.add(tf.keras.layers.Dense(units = 6 , activation = 'relu'))
model.add(tf.keras.layers.Dense(units = 1 , activation = 'sigmoid'))
# Compile the Model
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics=['accuracy'])
# Fit the Model
model.fit(x_train, y_train, batch_size=512, epochs =200)

In [11]:
y_pred = model.predict(x_test)
for i in range(len(y_pred)):
  if y_pred[i]>=0.5:
    y_pred[i]= 1
  else:
    y_pred[i] = 0  

y_pred.shape    

(2000, 1)

In [12]:

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.862

In [51]:

x_new = np.array([[600,'France','Male', 40, 3, 40000, 1, 2, 1, 50000],])
#x_new = pd.DataFrame(x_new)
# = x_new.iloc[0,0:].values
x_new[:,2]=label.transform(x_new[:,2])
#x_new = [[0,0, 600,'France','Male', 40, 3, 40000, 1, 2, 1, 50000]]
x_new = np.array(ct.transform(x_new))
x_new = [[0.,0.,1.0, 600,'0', 40, 3, 40000, 1, 2, 1, 50000]]
x_new = scaler.transform(x_new)
x_new

array([[-1.00280393, -0.57873591,  1.74273971, -0.52281016, -1.09598752,
         0.10281024, -0.69598177, 17.86397938, -0.91158349,  2.83995132,
         0.97024255, -0.87101922]])

In [52]:
y_pred_new = model.predict(x_new)
y_pred_new

array([[0.9919703]], dtype=float32)

In [53]:
data

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]